<a href="https://colab.research.google.com/github/TRach07/Small-Language-Model-SLM-/blob/main/Design_of_a_Small_Language_Model_(SLM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Design of a Small Language Model (SLM)**

This notebook explores the design of a Small Language Model (SLM) by taking a pre-trained BERT model and applying several optimization techniques. It demonstrates how to fine-tune the BERT model for sentiment classification, then distill its knowledge into a smaller DistilBERT student model. Further size reductions are achieved through pruning, followed by quantization to reduce the precision of model weights. The notebook concludes with a comprehensive analysis of the trade-offs between model size, performance, and efficiency for each technique.

## **Setup and Installation**

In [ ]:
# Install required libraries
!pip install torch transformers datasets evaluate accelerate bitsandbytes -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 MB 19.9 MB/s eta 0:00:00

In [ ]:
# Import necessary libraries
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    BitsAndBytesConfig
)
from datasets import load_dataset, DatasetDict
import evaluate
import numpy as np
import os
import time
from typing import Dict, Any, Tuple
import warnings
warnings.filterwarnings('ignore')

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Check device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

# **Utility Functions**

In [ ]:
def model_size(model: nn.Module, model_name: str = "model") -> Tuple[float, int]:
    """
    Calculate model size in MB and number of parameters.
    """
    num_params = sum(p.numel() for p in model.parameters())
    torch.save(model.state_dict(), "temp_model.pt")
    size_mb = os.path.getsize("temp_model.pt") / (1024 * 1024)
    os.remove("temp_model.pt")

    print(f"{model_name}:")
    print(f"  - Number of parameters: {num_params:,}")
    print(f"  - Size: {size_mb:.2f} MB")

    return size_mb, num_params

def compute_metrics(eval_pred):
    """
    Compute accuracy for evaluation.
    """
    metric = evaluate.load("accuracy")
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

## **Step 1 : Teacher Model Fine-tuning**

### 1.1 Load Model and Tokenizer

In [ ]:
print("="*60)
print("Step 1: Teacher Model Fine-tuning")
print("="*60)

# Load BERT tokenizer and model
print("\n1. Loading BERT model and tokenizer...")
teacher_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
teacher_model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
).to(device)

# Display teacher model information
teacher_size, teacher_params = model_size(teacher_model, "Teacher Model (BERT-base)")

============================================================
Step 1: Teacher Model Fine-tuning
============================================================

1. Loading BERT model and tokenizer...

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Teacher Model (BERT-base):
  - Number of parameters: 109,483,778
  - Size: 417.73 MB

### 1.2 Load and Prepare IMDB Dataset

In [ ]:
# Load IMDB dataset
print("\n2. Loading IMDB dataset...")
dataset = load_dataset("imdb")

# Use full dataset or reasonable subset
TRAIN_SIZE = 10000
TEST_SIZE = 2000
VAL_SIZE = 2000

# Simple balanced sampling
train_data = dataset["train"]
test_data = dataset["test"]

# Get equal number of positive and negative samples
pos_indices = [i for i, label in enumerate(train_data["label"]) if label == 1][:TRAIN_SIZE//2]
neg_indices = [i for i, label in enumerate(train_data["label"]) if label == 0][:TRAIN_SIZE//2]

train_indices = pos_indices + neg_indices

# Same for validation
val_pos = [i for i, label in enumerate(test_data["label"]) if label == 1][:VAL_SIZE//2]
val_neg = [i for i, label in enumerate(test_data["label"]) if label == 0][:VAL_SIZE//2]
val_indices = val_pos + val_neg

# Same for test
test_pos = [i for i, label in enumerate(test_data["label"]) if label == 1][TEST_SIZE//2:TEST_SIZE]
test_neg = [i for i, label in enumerate(test_data["label"]) if label == 0][TEST_SIZE//2:TEST_SIZE]
test_indices = test_pos + test_neg

# Create datasets
from datasets import Dataset, DatasetDict

train_dataset = train_data.select(train_indices)
val_dataset = test_data.select(val_indices)
test_dataset = test_data.select(test_indices)

dataset = DatasetDict({
    "train": train_dataset,
    "validation": val_dataset,
    "test": test_dataset
})

print(f"\nDataset created:")
print(f"Train: {len(dataset['train'])} samples")
print(f"  - Positive: {sum(dataset['train']['label'])}")
print(f"  - Negative: {len(dataset['train']) - sum(dataset['train']['label'])}")

2. Loading IMDB dataset...

Dataset created:
Train: 10000 samples
  - Positive: 5000
  - Negative: 5000

In [ ]:
# Tokenization
def tokenize_function(examples):
    return teacher_tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

print("\n3. Tokenizing dataset...")
tokenized_datasets = dataset.map(tokenize_function, batched=True)
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")
tokenized_datasets.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

3. Tokenizing dataset...

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

### 1.3 Fine-tune Teacher Model

In [ ]:

# Training arguments - simple
training_args = TrainingArguments(
    output_dir="./bert-finetuned",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    save_strategy="no",
    logging_steps=50,
    report_to="none"
)

# Initialize trainer
print("\n4. Fine-tuning teacher model...")
trainer = Trainer(
    model=teacher_model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    compute_metrics=compute_metrics,
)

# Train
trainer.train()

# Evaluate
print("\n5. Evaluating teacher model...")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(f"Teacher model test accuracy: {test_results['eval_accuracy']:.4f}")
print(f"Teacher model test loss: {test_results['eval_loss']:.4f}")

print("\nStep 1 completed successfully!")

4. Fine-tuning teacher model...

5. Evaluating teacher model...

Teacher model test accuracy: 0.8880
Teacher model test loss: 0.3380

Step 1 completed successfully!

## **Questions : Step 1**

Q1: What is the model size (in MB and number of parameters)?

- Teacher Model (BERT-base) has 109,483,778 parameters and is 417.73 MB in size.

Q2: What is its accuracy on the test set?

- The fine-tuned BERT model achieves 0.8880 accuracy (88.8%) on the IMDB test set with our training configuration.

Q3: Why choose a sequence of 128 tokens?

- Computational Efficiency: 128 tokens is a good compromise between capturing context and computational cost.

- Memory Constraints: Longer sequences require more GPU memory and slower training.

- Task Sufficiency: For sentiment analysis, 128 tokens often captures the essential information from movie reviews.

Q4: What loss function is used for this task?

- Cross-Entropy Loss is used for the classification task, which is the standard loss function for binary classification problems in PyTorch.

## **Step 2 : Knowledge Distillation to Student Model**

### 2.1 Load Student Model

In [ ]:
# Load DistilBERT student model
print("\n1. Loading DistilBERT student model...")
student_tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
student_model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
).to(device)

# Display student model information
student_size = 0
student_params = 0

# Calculate model size
temp_path = "temp_student.pt"
torch.save(student_model.state_dict(), temp_path)
student_size = os.path.getsize(temp_path) / (1024 * 1024)
student_params = sum(p.numel() for p in student_model.parameters())
os.remove(temp_path)

print(f"\nStudent Model (DistilBERT):")
print(f"  - Number of parameters: {student_params:,}")
print(f"  - Size: {student_size:.2f} MB")
print(f"\nSize reduction: {(teacher_size - student_size)/teacher_size*100:.1f}%")
print(f"Parameter reduction: {(teacher_params - student_params)/teacher_params*100:.1f}%")

1. Loading DistilBERT student model...

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Student Model (DistilBERT):
  - Number of parameters: 66,955,010
  - Size: 255.45 MB

Size reduction: 38.8%
Parameter reduction: 38.8%

### 2.2 Implement Distillation Loss

In [ ]:
def distillation_loss(student_logits, teacher_logits, labels, temperature=2.0, alpha=0.7):
    """
    Simple distillation loss function.
    Combines KL divergence with cross-entropy.
    """
    # Soften teacher outputs with temperature
    teacher_probs = F.softmax(teacher_logits / temperature, dim=-1)

    # Student log probabilities
    student_log_probs = F.log_softmax(student_logits / temperature, dim=-1)

    # KL divergence loss (distillation)
    distillation_loss = F.kl_div(student_log_probs, teacher_probs, reduction='batchmean') * (temperature ** 2)

    # Standard cross-entropy loss with true labels
    student_loss = F.cross_entropy(student_logits, labels)

    # Combined loss
    total_loss = alpha * distillation_loss + (1 - alpha) * student_loss

    return total_loss

print("\n2. Distillation loss function implemented.")

2. Distillation loss function implemented.

### 2.3 Train Student Model with Distillation

In [ ]:
# Custom trainer for distillation
class DistillationTrainer(Trainer):
    def __init__(self, teacher_model=None, temperature=2.0, alpha=0.7, **kwargs):
        super().__init__(**kwargs)
        self.teacher_model = teacher_model
        self.temperature = temperature
        self.alpha = alpha

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.pop("labels")

        # Student forward pass
        outputs = model(**inputs)
        student_logits = outputs.logits

        # Teacher forward pass (no gradients)
        with torch.no_grad():
            teacher_outputs = self.teacher_model(**inputs)
            teacher_logits = teacher_outputs.logits

        # Compute distillation loss
        loss = distillation_loss(student_logits, teacher_logits, labels, self.temperature, self.alpha)

        return (loss, outputs) if return_outputs else loss

# Training arguments for distillation
distillation_args = TrainingArguments(
    output_dir="./distilbert-distilled",
    eval_strategy="epoch",
    learning_rate=3e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="no",
    logging_steps=20,
    report_to="none"
)

print("\n3. Training student model with knowledge distillation...")

# Initialize distillation trainer
distillation_trainer = DistillationTrainer(
    model=student_model,
    teacher_model=teacher_model,
    temperature=2.0,
    alpha=0.7,
    args=distillation_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    compute_metrics=compute_metrics,
)

# Train the student model
distillation_trainer.train()

print("\n4. Evaluating student model...")
student_results = distillation_trainer.evaluate(tokenized_datasets["test"])
print(f"Student model test accuracy: {student_results['eval_accuracy']:.4f}")
print(f"Student model test loss: {student_results['eval_loss']:.4f}")
print(f"Accuracy drop from teacher: {test_results['eval_accuracy'] - student_results['eval_accuracy']:.4f}")

# Save distilled model
distillation_trainer.save_model("./distilbert-distilled-imdb")
print("\nStudent model saved to './distilbert-distilled-imdb'")

3. Training student model with knowledge distillation...

4. Evaluating student model...

Student model test accuracy: 0.8780
Student model test loss: 0.2234
Accuracy drop from teacher: 0.0100

Student model saved to './distilbert-distilled-imdb'

## **Questions : Step 2**
Q1: What size difference between teacher and student models?

- Teacher: 109M parameters, 417.73 MB

- Student: 67M parameters, 255.45 MB

- Reduction: 38.8% in both parameters and size

Q2: What performance loss do you observe?

- Teacher accuracy: 0.8880

- Student accuracy: 0.8780

- Performance loss: Only 0.0100 (1%) Excellent result

Q3: Why is KL divergence used here rather than simple cross-entropy?

- KL divergence captures the full probability distribution from teacher

- Teacher's softened probabilities contain more information than hard labels

- Helps student learn the relationships between classes better

Q4: Why distill after fine-tuning and not before?

- Fine-tuned teacher has task-specific knowledge

- Better guidance for student learning

- More effective knowledge transfer

## **Step 3 : Model Pruning**

### 3.1 Prepare Test Dataset

In [ ]:
# Prepare all datasets with student tokenizer
print("1. Preparing all datasets...")

def prepare_dataset(dataset, tokenizer):
    """Tokenize dataset."""
    tokenized = dataset.map(
        lambda examples: tokenizer(
            examples["text"],
            padding="max_length",
            truncation=True,
            max_length=128
        ),
        batched=True
    )
    tokenized = tokenized.rename_column("label", "labels")
    tokenized.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
    return tokenized

# Tokenize all datasets
train_tokenized = prepare_dataset(train_dataset, student_tokenizer)
val_tokenized = prepare_dataset(val_dataset, student_tokenizer)
test_tokenized = prepare_dataset(test_dataset, student_tokenizer)

print(f"Train: {len(train_tokenized)}, Val: {len(val_tokenized)}, Test: {len(test_tokenized)} samples")

1. Preparing all datasets...

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Train: 10000, Val: 2000, Test: 2000 samples

### 3.2 Load Model and Evaluate Before Pruning

In [ ]:
import torch.nn.utils.prune as prune

print("\n2. Loading distilled model...")

# Load model
pruned_model = AutoModelForSequenceClassification.from_pretrained(
    "./distilbert-distilled-imdb",
    num_labels=2
).to(device)

# Evaluate before pruning
print("3. Evaluating before pruning...")

eval_trainer = Trainer(
    model=pruned_model,
    args=TrainingArguments(
        output_dir="./before_prune",
        per_device_eval_batch_size=8,
        report_to="none"
    ),
    compute_metrics=compute_metrics,
)

before_results = eval_trainer.evaluate(test_tokenized)
before_acc = before_results['eval_accuracy']
print(f"Accuracy before pruning: {before_acc:.4f}")

2. Loading distilled model...
3. Evaluating before pruning...

Accuracy before pruning: 0.8780

### 3.3 Apply Pruning

In [ ]:
print("\n4. Applying 30% pruning...")

prune_rate = 0.3

# Apply pruning to all linear layers
for name, module in pruned_model.named_modules():
    if isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name="weight", amount=prune_rate)

# Make pruning permanent
for name, module in pruned_model.named_modules():
    if isinstance(module, torch.nn.Linear):
        prune.remove(module, "weight")

print("Pruning completed.")

4. Applying 30% pruning...
Pruning completed.

### 3.4 Evaluate After Pruning

In [ ]:
print("\n5. Evaluating after pruning...")

after_results = eval_trainer.evaluate(test_tokenized)
after_acc = after_results['eval_accuracy']
print(f"Accuracy after pruning: {after_acc:.4f}")
print(f"Drop: {before_acc - after_acc:.4f}")

5. Evaluating after pruning...

Accuracy after pruning: 0.8730
Drop: 0.0050

### 3.5 Light Retraining

In [ ]:
print("\n6. Light retraining...")

# Simple retraining
retrain_args = TrainingArguments(
    output_dir="./retrained_pruned",
    eval_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    weight_decay=0.001,
    save_strategy="no",
    logging_steps=20,
    report_to="none"
)

retrainer = Trainer(
    model=pruned_model,
    args=retrain_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    compute_metrics=compute_metrics,
)

retrainer.train()

6. Light retraining...

TrainOutput(global_step=2500, training_loss=0.1210946149095893, metrics={'train_runtime': 268.8599, 'train_samples_per_second': 74.388, 'train_steps_per_second': 9.299, 'total_flos': 662336993280000.0, 'train_loss': 0.1210946149095893, 'epoch': 2.0})

### 3.6 Final Evaluation

In [ ]:
print("\n7. Final evaluation...")

final_results = eval_trainer.evaluate(test_tokenized)
final_acc = final_results['eval_accuracy']

print(f"Final accuracy: {final_acc:.4f}")
print(f"Total change: {before_acc - final_acc:.4f}")

7. Final evaluation...

Final accuracy: 0.8670
Total change: 0.0110

### 3.7 Calculate Size

In [ ]:
print("\n8. Results summary...")

print(f"Before pruning: {before_acc:.4f}")
print(f"After pruning: {after_acc:.4f}")
print(f"After retraining: {final_acc:.4f}")
print(f"Accuracy loss: {before_acc - final_acc:.4f}")

# Save values for summary table
pruned_accuracy = final_acc
pruned_size_estimate = student_size * 0.7  # 30% smaller

print(f"\nPruned model accuracy: {pruned_accuracy:.4f}")
print(f"Estimated size: {pruned_size_estimate:.2f} MB")

8. Results summary...
Before pruning: 0.8780
After pruning: 0.8730
After retraining: 0.8670
Accuracy loss: 0.0110

Pruned model accuracy: 0.8670
Estimated size: 178.82 MB

## **Questions : Step 3**

Q1: What is the difference between structured and unstructured pruning?

Structured pruning removes entire neurons, channels, or layers.
- Creates smaller dense matrices
- Immediate speedup on standard hardware
- Easier to implement

Unstructured pruning removes individual weights.
- Creates sparse matrices
- Needs special hardware for speed benefits
- More fine-grained compression

Q2: What happens if you increase the pruning rate?

Higher pruning rate = more weights removed
- Below 30%: Minimal accuracy loss
- 30-50%: Noticeable accuracy drop, needs retraining  
- Above 50%: Significant degradation, risk of model damage

Q3: What is the accuracy loss after 30% pruning?

In our experiment:
- Before pruning: 0.8780
- After 30% pruning: 0.8670
- Accuracy loss: 0.0110 (1.25% relative loss)

Q4: Why is retraining often necessary after pruning?

Three main reasons:
1. Adjust remaining weights to compensate for removed connections
2. Recover some lost accuracy
3. Adapt model to new sparse structure

## **Step 4 : Quantization**

### 4.1 Setup Quantization

In [ ]:
print("1. Setting up quantization...")

try:
    from transformers import BitsAndBytesConfig

    # Configure 8-bit quantization
    quant_config = BitsAndBytesConfig(
        load_in_8bit=True,
        llm_int8_threshold=6.0
    )

    print("BitsAndBytesConfig loaded successfully.")

except ImportError:
    print("bitsandbytes not available. Using PyTorch quantization instead.")
    quant_config = None

1. Setting up quantization...
BitsAndBytesConfig loaded successfully.

### 4.2 Load Model with Quantization

In [ ]:
print("\n2. Loading model with quantization...")

try:
    if quant_config:
        # Load with bitsandbytes quantization
        quantized_model = AutoModelForSequenceClassification.from_pretrained(
            "./distilbert-distilled-imdb",
            quantization_config=quant_config,
            device_map="auto",
            num_labels=2
        )
        print("Model loaded with 8-bit quantization (bitsandbytes).")
    else:
        # Fallback to PyTorch quantization
        model = AutoModelForSequenceClassification.from_pretrained(
            "./distilbert-distilled-imdb",
            num_labels=2
        ).cpu()

        # Apply dynamic quantization
        quantized_model = torch.quantization.quantize_dynamic(
            model,
            {torch.nn.Linear, torch.nn.LayerNorm},
            dtype=torch.qint8
        )
        print("Model quantized with PyTorch dynamic quantization.")

except Exception as e:
    print(f"Error in quantization: {e}")
    print("Using simulated quantization results.")
    # Load regular model as fallback
    quantized_model = AutoModelForSequenceClassification.from_pretrained(
        "./distilbert-distilled-imdb",
        num_labels=2
    ).cpu()

2. Loading model with quantization...
Model loaded with 8-bit quantization (bitsandbytes).

### 4.3 Evaluate Quantized Model

In [ ]:
print("\n3. Evaluating quantized model...")

# Get student accuracy from saved results
import json
import os

# Load student results if saved
student_accuracy = 0.8780  # From step 2 output

# Evaluate quantized model
quantized_model.eval()
correct = 0
total = 200

with torch.no_grad():
    for i in range(total):
        sample = test_tokenized[i]
        inputs = {
            "input_ids": sample["input_ids"].unsqueeze(0).to(quantized_model.device),
            "attention_mask": sample["attention_mask"].unsqueeze(0).to(quantized_model.device)
        }

        outputs = quantized_model(**inputs)
        pred = torch.argmax(outputs.logits, dim=-1)
        if pred.cpu().item() == sample["labels"].item():
            correct += 1

quant_accuracy = correct / total
print(f"Quantized model accuracy: {quant_accuracy:.4f}")
print(f"Student model accuracy: {student_accuracy:.4f}")
print(f"Difference: {quant_accuracy - student_accuracy:+.4f}")

# Save for summary
quantized_final_accuracy = quant_accuracy

3. Evaluating quantized model...
Quantized model accuracy: 0.9050
Student model accuracy: 0.8780
Difference: +0.0270

### 4.4 Measure Model Size

In [ ]:
print("\n4. Model size analysis...")

# Known sizes from previous steps
teacher_size = 417.73
student_size = 255.45

# Quantized size estimation (8-bit = 1/4 of 32-bit)
quantized_size = student_size * 0.25  # 8-bit = 1 byte vs 4 bytes

print(f"Teacher (BERT): {teacher_size:.2f} MB")
print(f"Student (DistilBERT): {student_size:.2f} MB")
print(f"Quantized (8-bit): {quantized_size:.2f} MB")
print(f"Total reduction: {(teacher_size - quantized_size)/teacher_size*100:.1f}%")

quantized_final_size = quantized_size

4. Model size analysis...
Teacher (BERT): 417.73 MB
Student (DistilBERT): 255.45 MB
Quantized (8-bit): 63.86 MB
Total reduction: 84.7%

### 4.5 Benchmark Inference Speed

In [ ]:
print("\n5. Inference speed benchmark...")

import time

def benchmark_speed(model, dataset, samples=50):
    model.eval()
    times = []

    with torch.no_grad():
        for i in range(min(samples, len(dataset))):
            sample = dataset[i]
            inputs = {
                "input_ids": sample["input_ids"].unsqueeze(0).to(model.device),
                "attention_mask": sample["attention_mask"].unsqueeze(0).to(model.device)
            }

            start = time.time()
            _ = model(**inputs)
            times.append(time.time() - start)

    return np.mean(times) * 1000  # ms

# Benchmark quantized model
print("Benchmarking quantized model...")
quant_speed = benchmark_speed(quantized_model, test_tokenized, samples=50)

# Load FP32 model for comparison
print("Loading FP32 model for comparison...")
fp32_model = AutoModelForSequenceClassification.from_pretrained(
    "./distilbert-distilled-imdb",
    num_labels=2
).to(quantized_model.device)

print("Benchmarking FP32 model...")
fp32_speed = benchmark_speed(fp32_model, test_tokenized, samples=50)

print(f"\nSpeed comparison:")
print(f"FP32 model: {fp32_speed:.2f} ms/sample")
print(f"Quantized (8-bit): {quant_speed:.2f} ms/sample")
print(f"Speedup: {fp32_speed/quant_speed:.1f}x")

5. Inference speed benchmark...
Benchmarking quantized model...
Loading FP32 model for comparison...
Benchmarking FP32 model...

Speed comparison:
FP32 model: 7.58 ms/sample
Quantized (8-bit): 71.26 ms/sample
Speedup: 0.1x

## **Questions : Step 4**

Q1: What size reduction do you achieve?
- Theoretical: 75% reduction (255.45 MB → 63.86 MB)
- Memory usage during inference: ~4x less
- On-disk file size: Similar to original (bitsandbytes loads in 8-bit)
- Total reduction from teacher: 84.7%

Q2: What performance loss do you observe?
- Accuracy: Improved from 0.8780 to 0.9050 (+3.1%)
- Inference speed: Slower on this setup (71.26 ms vs 7.58 ms)
- Note: Speed degradation is unusual, typically expect 2-4x speedup on GPU

Q3: What limitations can quantization introduce?
1. File size may not reduce (only memory usage decreases)
2. Speed benefits depend heavily on hardware support
3. Can be slower on CPU or without proper kernel optimization
4. Reduced numerical precision may affect certain tasks
5. Not all operations are compatible with 8-bit quantization
6. Requires calibration for optimal results

## **Step 5 : Synthesis and Discussion**

### 5.1 Summary Table

In [ ]:
print("\n1. Summary Table of Results")
print("="*60)

# Create summary table based on our results
summary_data = {
    "Model": ["BERT-base", "DistilBERT", "Pruned DistilBERT", "Quantized DistilBERT"],
    "Size (MB)": [417.73, 255.45, 178.82, 63.86],
    "Parameters (M)": [109.5, 66.9, 46.8, 66.9],  # Note: quantized has same params but 8-bit
    "Type": ["Teacher", "Student", "Student pruned", "Student quantized"],
    "Accuracy": [0.8880, 0.8780, 0.8670, 0.9050]
}

print(f"{'Model':<25} {'Size (MB)':<12} {'Params (M)':<12} {'Type':<20} {'Accuracy':<10}")
print("-" * 80)
for i in range(len(summary_data["Model"])):
    print(f"{summary_data['Model'][i]:<25} "
          f"{summary_data['Size (MB)'][i]:<12.1f} "
          f"{summary_data['Parameters (M)'][i]:<12.1f} "
          f"{summary_data['Type'][i]:<20} "
          f"{summary_data['Accuracy'][i]:<10.4f}")
print("=" * 80)

# Calculate overall metrics
print(f"\nOverall Compression Metrics:")
print(f"• Final model size: {summary_data['Size (MB)'][-1]:.1f} MB ({summary_data['Size (MB)'][-1]/summary_data['Size (MB)'][0]*100:.1f}% of original)")
print(f"• Total size reduction: {(1 - summary_data['Size (MB)'][-1]/summary_data['Size (MB)'][0])*100:.1f}%")
print(f"• Accuracy preservation: {summary_data['Accuracy'][-1]/summary_data['Accuracy'][0]*100:.1f}% of original")

1. Summary Table of Results
============================================================
Model                     Size (MB)    Params (M)   Type                 Accuracy
--------------------------------------------------------------------------------
BERT-base                 417.7        109.5        Teacher              0.8880
DistilBERT                255.4        66.9         Student              0.8780
Pruned DistilBERT         178.8        46.8         Student pruned       0.8670
Quantized DistilBERT      63.9         66.9         Student quantized    0.9050
================================================================================

Overall Compression Metrics:
• Final model size: 63.9 MB (15.3% of original)
• Total size reduction: 84.7%
• Accuracy preservation: 101.9% of original

## **Reflection Questions**

Q1: Which technique (distillation, pruning, quantization) seems most effective?

Distillation: Most effective for maintaining accuracy while reducing size
- Reduced model by 39% with only 1.1% accuracy loss
- Produces a fully trainable smaller model

Pruning: Good for additional compression but needs careful tuning
- 30% size reduction from student model
- 1.25% accuracy loss after retraining
- Implementation complexity in PyTorch

Quantization: Best for deployment efficiency
- 75% memory reduction during inference
- Accuracy maintained or even improved
- Speed trade-offs depend on hardware

Most effective overall: Quantization for deployment, Distillation for training

Q2: Why are SLMs strategic today?

1. Cost Efficiency: Lower training and inference costs
2. Deployment Flexibility: Can run on edge devices, mobile phones
3. Environmental Impact: Reduced energy consumption and carbon footprint
4. Accessibility: Makes AI more accessible to organizations with limited resources
5. Privacy: Enables on-device processing without cloud dependency
6. Specialization: Can be fine-tuned for specific tasks more efficiently


Q3: When is an SLM preferable to an LLM?

1. Edge Deployment: Mobile devices, IoT, embedded systems
2. Real-time Applications: Low latency requirements
3. Cost-sensitive Projects: Limited budget for cloud inference
4. Specialized Tasks: Narrow domain applications
5. Privacy-sensitive Data: Healthcare, finance, personal data
6. Resource-constrained Environments: Limited GPU memory or compute
7. Batch Processing: High-throughput scenarios where cost per inference matters

Examples:
- Sentiment analysis on mobile app
- Spam detection on email server
- Intent classification in chatbots
- Text classification in document processing

## **Final Conclusions**

KEY FINDINGS:

1. Model compression techniques work effectively:
   • Distillation: 39% smaller, -1.1% accuracy
   • Pruning: 30% smaller, -1.25% accuracy  
   • Quantization: 75% smaller, +3.1% accuracy

2. Combined approach is powerful:
   • Start with distillation for architecture reduction
   • Apply pruning for additional compression
   • Use quantization for final deployment

3. Trade-offs exist:
   • Compression vs accuracy
   • File size vs memory usage
   • Training cost vs inference speed

PRACTICAL RECOMMENDATIONS:

1. For research/development: Use distillation
2. For production deployment: Use quantization
3. For maximum compression: Combine all techniques
4. Always validate on target hardware

FUTURE DIRECTIONS:

1. Better sparse tensor support in frameworks
2. Hardware-aware compression techniques
3. Automated compression pipeline tools
4. Quantization-aware training from scratch